### ISSUE TITLE
Update to 1.19.2

### ISSUE THREAD

**Issue by Sunconure11** [bottledspace/ottercraft#14]
At this point, it's stable. Perhaps it is time for an update? @bottledspace @astronotter

**Comment by bottledspace** [comment]
A good plan, just a matter of free time I'm afraid :)

**Comment by Sunconure11** [comment]
It is not that big of a port

**Comment by bottledspace** [comment]
That's good to hear. I still won't have time to look into it for a few weeks at least. Feel free to submit a PR in the meantime.

**Comment by bottledspace** [comment]
Sorry for the wait. See the latest release here or on Curseforge for the updated jars :)

**Comment by Sunconure11** [comment]
Might want to add a 1.19.2 build, too. Some mod devs are refusing to update to 1.19.3, so I'm kind of... stuck.

**Comment by bottledspace** [comment]
I have added builds for 1.19.2 to the latest release.
