### ISSUE TITLE
1.20+?

### ISSUE THREAD

**Issue by SuperStefan97** [bottledspace/ottercraft#21]
Hi! A lot of people love your mod. Will there ever be a 1.20+ version or is the mod in oblivion? Also, if you haven't abandoned this mod... would you port it to NeoForge instead of Forge?

**Comment by bottledspace** [comment]
Hi, thanks for reaching out. The mod isn't abandoned and I'll update when I can but it may be a while yet unfortunately, as I'm busy working on my Master's thesis right now :)

**Comment by SuperStefan97** [comment]
I just saw this! Congrats on your master! Personaly just made my own so I so damn understand you. I'm also glad to see a new build for fabric. You might be a little out dated about recent modding, but if you could do it for NeoForge 1.20.1 is one of the most played (if not the most) versions of forge would be greatly appreciated

**Comment by bottledspace** [comment]
The majority of our userbase seems to be using Fabric for whatever reason according to the downloads so I start with that one but I plan to update Forge too don't worry :)

**Comment by SuperStefan97** [comment]
Thanks! Sadly, Forge and Neo are compatible until 1.20.1, from that up they split. Most if not all Forge big mods (Alex's Mods, Twilight Forest, Aether...) stayed at 1.20.1 Neo/Forge

**Comment by bottledspace** [comment]
Added a Backport to 1.20.1 for (Neo)Forge on CF, seems to work from my quick test but reopen if you find any issues.

**Comment by SuperStefan97** [comment]
Thank you very much for taking the time!!
