### ISSUE TITLE
[SUGGESTION] Otter variants based on biome

### ISSUE THREAD

**Issue by Sunconure11** [bottledspace/ottercraft#4]
Otters are not a single species... and I feel like that could be represented here.

Amazon giant otters: Could be a variant for jungles. Also, could be the biggest of the variants.

Sea otters: Variant for beaches and lukewarm oceans

Eurasian otter: Variant for colder biomes

Smooth-coated otter: Variant for temperate biomes

There are other species, but many would overlap with these, or aren't simply unique enough

**Comment by astronotter** [comment]
Thanks for the suggestions, we have had giant otters planned in a future update for a while (see the the Curseforge page). Just a matter of getting the time. :)
